version: '3.8'

services:
  app:
    build: .
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    environment:
      MONGO_DB_USERNAME: admin
      MONGO_DB_PASSWORD: qwerty
    volumes:
      - .:/app

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/

volumes:
  mongo_data:
